//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.ServiceAuthenticationReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserValidation", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum UserValidation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegistrationSuccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterSuccess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginAlreadyExists = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAuthenticationReference.IServiceAuthentication")]
    public interface IServiceAuthentication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/GetData", ReplyAction="http://tempuri.org/IServiceAuthentication/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/GetData", ReplyAction="http://tempuri.org/IServiceAuthentication/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAuthentication/GetDataUsingDataContractResponse")]
        ChatClient.ServiceAuthenticationReference.CompositeType GetDataUsingDataContract(ChatClient.ServiceAuthenticationReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAuthentication/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.CompositeType> GetDataUsingDataContractAsync(ChatClient.ServiceAuthenticationReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/RegisterUser", ReplyAction="http://tempuri.org/IServiceAuthentication/RegisterUserResponse")]
        ChatClient.ServiceAuthenticationReference.UserValidation RegisterUser(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/RegisterUser", ReplyAction="http://tempuri.org/IServiceAuthentication/RegisterUserResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.UserValidation> RegisterUserAsync(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/Enter", ReplyAction="http://tempuri.org/IServiceAuthentication/EnterResponse")]
        ChatClient.ServiceAuthenticationReference.UserValidation Enter(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthentication/Enter", ReplyAction="http://tempuri.org/IServiceAuthentication/EnterResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.UserValidation> EnterAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAuthenticationChannel : ChatClient.ServiceAuthenticationReference.IServiceAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAuthenticationClient : System.ServiceModel.ClientBase<ChatClient.ServiceAuthenticationReference.IServiceAuthentication>, ChatClient.ServiceAuthenticationReference.IServiceAuthentication {
        
        public ServiceAuthenticationClient() {
        }
        
        public ServiceAuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ChatClient.ServiceAuthenticationReference.CompositeType GetDataUsingDataContract(ChatClient.ServiceAuthenticationReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.CompositeType> GetDataUsingDataContractAsync(ChatClient.ServiceAuthenticationReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ChatClient.ServiceAuthenticationReference.UserValidation RegisterUser(string login, string pass) {
            return base.Channel.RegisterUser(login, pass);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.UserValidation> RegisterUserAsync(string login, string pass) {
            return base.Channel.RegisterUserAsync(login, pass);
        }
        
        public ChatClient.ServiceAuthenticationReference.UserValidation Enter(string login, string password) {
            return base.Channel.Enter(login, password);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceAuthenticationReference.UserValidation> EnterAsync(string login, string password) {
            return base.Channel.EnterAsync(login, password);
        }
    }
}
