//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.ReadMessages = new HashSet<ReadMessage>();
        }
    
        public int Id { get; set; }
        public int UserFrom_Id { get; set; }
        public Nullable<int> UserTo_Id { get; set; }
        public Nullable<int> GroupTo_Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadMessage> ReadMessages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
